---
id: sezemi-2014-readable-code-1-retrospective
base_name: how-to-look-back
tags:
- rabbit
- readable-code
- sezemi
presentation_date: 2014-06-22
version: 2014.6.22.3
licenses:
- CC BY-SA 4.0
slideshare_id: sezemi-2014-readable-code-1-retrospective
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
